# Generated by Django 3.2.6 on 2021-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='pieces',
        ),
        migrations.AddField(
            model_name='terminal',
            name='hello',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
