# Generated by Django 3.2.6 on 2021-08-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20210818_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='hello',
        ),
        migrations.AddField(
            model_name='terminal',
            name='ip',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='terminal',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='terminal',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
