# Generated by Django 3.2.6 on 2021-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='password',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='username',
        ),
        migrations.AddField(
            model_name='terminal',
            name='ram',
            field=models.IntegerField(null=True, verbose_name='Amount of Ram'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='vulnerability',
            field=models.CharField(default='', max_length=50, verbose_name='Type of Vulnerability'),
        ),
    ]
