# Generated by Django 3.2.6 on 2021-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_auto_20210819_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='core',
            field=models.IntegerField(default='2', null=True, verbose_name='Cpu Core'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ram',
            field=models.IntegerField(default='1024', null=True, verbose_name='Amount of Ram'),
        ),
    ]
